const memberData = [
  {
    "index": 1,
    "name_ch": "梁君彥",
    "name_en": "Andrew LEUNG",
    "title": "梁君彥, Andrew LEUNG",
    "summary": "Functional Constituency - Industrial (First)",
    "image": "https://www.legco.gov.hk/images/mem_1620/lky.jpg",
    "camp": "pro-establishment",
    "coord1D": "",
    "coord2D": ""
  },
  {
    "index": 2,
    "name_ch": "涂謹申",
    "name_en": "James TO",
    "title": "涂謹申, James TO",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.636268079,
    "coord2D": -0.148295313
  },
  {
    "index": 3,
    "name_ch": "梁耀忠",
    "name_en": "LEUNG Yiu-chung",
    "title": "梁耀忠, LEUNG Yiu-chung",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.884833753,
    "coord2D": -0.048161693
  },
  {
    "index": 4,
    "name_ch": "石禮謙",
    "name_en": "Abraham SHEK",
    "title": "石禮謙, Abraham SHEK",
    "summary": "Functional Constituency - Real Estate and Construction",
    "image": "https://www.legco.gov.hk/images/mem_1620/slh.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.904187918,
    "coord2D": 0.300936401
  },
  {
    "index": 5,
    "name_ch": "張宇人",
    "name_en": "Tommy CHEUNG",
    "title": "張宇人, Tommy CHEUNG",
    "summary": "Functional Constituency - Catering",
    "image": "https://www.legco.gov.hk/images/mem_1620/cyy.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.970492303,
    "coord2D": 0.241132408
  },
  {
    "index": 6,
    "name_ch": "李國麟",
    "name_en": "Prof Joseph LEE",
    "title": "李國麟, Prof Joseph LEE",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.554540396,
    "coord2D": 0.266916782
  },
  {
    "index": 7,
    "name_ch": "林健鋒",
    "name_en": "Jeffrey LAM",
    "title": "林健鋒, Jeffrey LAM",
    "summary": "Functional Constituency - Commercial (First)",
    "image": "https://www.legco.gov.hk/images/mem_1620/lkf.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.945977449,
    "coord2D": 0.062668927
  },
  {
    "index": 8,
    "name_ch": "黃定光",
    "name_en": "WONG Ting-kwong",
    "title": "黃定光, WONG Ting-kwong",
    "summary": "Functional Constituency - Import and Export",
    "image": "https://www.legco.gov.hk/images/mem_small_1620/wtk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.800210476,
    "coord2D": -0.134095222
  },
  {
    "index": 9,
    "name_ch": "李慧琼",
    "name_en": "Starry LEE",
    "title": "李慧琼, Starry LEE",
    "summary": "Functional Constituency - District Council (Second)",
    "image": "https://www.legco.gov.hk/images/mem_1620/lwks.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.775083482,
    "coord2D": -0.205036506
  },
  {
    "index": 10,
    "name_ch": "陳克勤",
    "name_en": "CHAN Hak-kan",
    "title": "陳克勤, CHAN Hak-kan",
    "summary": "Geographical Constituency - New Territories East",
    "image": "https://www.legco.gov.hk/images/mem_1620/chk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.779792964,
    "coord2D": -0.208714709
  },
  {
    "index": 11,
    "name_ch": "陳健波",
    "name_en": "CHAN Kin-por",
    "title": "陳健波, CHAN Kin-por",
    "summary": "Functional Constituency - Insurance",
    "image": "https://www.legco.gov.hk/images/mem_1620/ckp.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.890700102,
    "coord2D": 0.053718153
  },
  {
    "index": 12,
    "name_ch": "梁美芬",
    "name_en": "Dr Priscilla LEUNG",
    "title": "梁美芬, Dr Priscilla LEUNG",
    "summary": "Geographical Constituency - Kowloon West",
    "image": "https://www.legco.gov.hk/images/mem_1620/lmf.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.827820897,
    "coord2D": 0.025708398
  },
  {
    "index": 13,
    "name_ch": "黃國健",
    "name_en": "WONG Kwok-kin",
    "title": "黃國健, WONG Kwok-kin",
    "summary": "Geographical Constituency - Kowloon East",
    "image": "https://www.legco.gov.hk/images/mem_small_1620/wkk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.726251245,
    "coord2D": -0.325166196
  },
  {
    "index": 14,
    "name_ch": "葉劉淑儀",
    "name_en": "Mrs Regina IP",
    "title": "葉劉淑儀, Mrs Regina IP",
    "summary": "Geographical Constituency - Hong Kong Island",
    "image": "https://www.legco.gov.hk/images/mem_1620/ilsy.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.787508547,
    "coord2D": 0.267949402
  },
  {
    "index": 15,
    "name_ch": "謝偉俊",
    "name_en": "Paul TSE",
    "title": "謝偉俊, Paul TSE",
    "summary": "Geographical Constituency – Kowloon East",
    "image": "https://www.legco.gov.hk/images/mem_small_1620/twc.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.756919384,
    "coord2D": 0.353179216
  },
  {
    "index": 16,
    "name_ch": "毛孟靜",
    "name_en": "Claudia MO",
    "title": "毛孟靜, Claudia MO",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.854045033,
    "coord2D": -0.058279511
  },
  {
    "index": 17,
    "name_ch": "田北辰",
    "name_en": "Michael TIEN",
    "title": "田北辰, Michael TIEN",
    "summary": "Geographical Constituency – New Territories West",
    "image": "https://www.legco.gov.hk/images/mem_1620/tps.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.703049302,
    "coord2D": 0.14968206
  },
  {
    "index": 18,
    "name_ch": "何俊賢",
    "name_en": "Steven HO",
    "title": "何俊賢, Steven HO",
    "summary": "Functional Constituency - Agriculture and Fisheries",
    "image": "https://www.legco.gov.hk/images/mem_1620/hcys.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.790566325,
    "coord2D": -0.204959959
  },
  {
    "index": 19,
    "name_ch": "易志明",
    "name_en": "Frankie YICK",
    "title": "易志明, Frankie YICK",
    "summary": "Functional Constituency - Transport",
    "image": "https://www.legco.gov.hk/images/mem_1620/ycm.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.944634616,
    "coord2D": 0.328124374
  },
  {
    "index": 20,
    "name_ch": "胡志偉",
    "name_en": "WU Chi-wai",
    "title": "胡志偉, WU Chi-wai",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.647269547,
    "coord2D": -0.111071318
  },
  {
    "index": 21,
    "name_ch": "姚思榮",
    "name_en": "YIU Si-wing",
    "title": "姚思榮, YIU Si-wing",
    "summary": "Functional Constituency - Tourism",
    "image": "https://www.legco.gov.hk/images/mem_1620/ysw.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.940043986,
    "coord2D": 0.121908128
  },
  {
    "index": 22,
    "name_ch": "馬逢國",
    "name_en": "MA Fung-kwok",
    "title": "馬逢國, MA Fung-kwok",
    "summary": "Functional Constituency - Sports, Performing Arts, Culture and Publication",
    "image": "https://www.legco.gov.hk/images/mem_1620/mfk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.891019166,
    "coord2D": 0.060216554
  },
  {
    "index": 23,
    "name_ch": "莫乃光",
    "name_en": "Charles Peter MOK",
    "title": "莫乃光, Charles Peter MOK",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.563915372,
    "coord2D": 0.304872304
  },
  {
    "index": 24,
    "name_ch": "陳志全",
    "name_en": "CHAN Chi-chuen",
    "title": "陳志全, CHAN Chi-chuen",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.929577947,
    "coord2D": -0.201871127
  },
  {
    "index": 25,
    "name_ch": "陳恒鑌",
    "name_en": "CHAN Han-pan",
    "title": "陳恒鑌, CHAN Han-pan",
    "summary": "Geographical Constituency – New Territories West",
    "image": "https://www.legco.gov.hk/images/mem_1620/chp.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.782775819,
    "coord2D": -0.214242473
  },
  {
    "index": 26,
    "name_ch": "梁志祥",
    "name_en": "LEUNG Che-cheung",
    "title": "梁志祥, LEUNG Che-cheung",
    "summary": "Geographical Constituency - New Territories West",
    "image": "https://www.legco.gov.hk/images/mem_1620/lcc.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.796828926,
    "coord2D": -0.199281707
  },
  {
    "index": 27,
    "name_ch": "梁繼昌",
    "name_en": "Kenneth LEUNG",
    "title": "梁繼昌, Kenneth LEUNG",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.537863791,
    "coord2D": 0.376491845
  },
  {
    "index": 28,
    "name_ch": "麥美娟",
    "name_en": "Alice MAK",
    "title": "麥美娟, Alice MAK",
    "summary": "Geographical Constituency – New Territories West",
    "image": "https://www.legco.gov.hk/images/mem_1620/mmk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.721752822,
    "coord2D": -0.314466268
  },
  {
    "index": 29,
    "name_ch": "郭家麒",
    "name_en": "Dr KWOK Ka-ki",
    "title": "郭家麒, Dr KWOK Ka-ki",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.754679024,
    "coord2D": -0.105571985
  },
  {
    "index": 30,
    "name_ch": "郭偉强",
    "name_en": "KWOK Wai-keung",
    "title": "郭偉强, KWOK Wai-keung",
    "summary": "Geographical Constituency - Hong Kong Island",
    "image": "https://www.legco.gov.hk/images/mem_1620/kwk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.718087673,
    "coord2D": -0.346333474
  },
  {
    "index": 31,
    "name_ch": "郭榮鏗",
    "name_en": "Dennis KWOK",
    "title": "郭榮鏗, Dennis KWOK",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.768305361,
    "coord2D": -0.023424558
  },
  {
    "index": 32,
    "name_ch": "張華峰",
    "name_en": "Christopher CHEUNG",
    "title": "張華峰, Christopher CHEUNG",
    "summary": "Functional Constituency - Financial Services",
    "image": "https://www.legco.gov.hk/images/mem_1620/cwf.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.887148976,
    "coord2D": 0.068941563
  },
  {
    "index": 33,
    "name_ch": "張超雄",
    "name_en": "Dr Fernando CHEUNG",
    "title": "張超雄, Dr Fernando CHEUNG",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.872726202,
    "coord2D": 0.117681794
  },
  {
    "index": 34,
    "name_ch": "黃碧雲",
    "name_en": "Dr Helena WONG",
    "title": "黃碧雲, Dr Helena WONG",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.632858872,
    "coord2D": -0.151776433
  },
  {
    "index": 35,
    "name_ch": "葉建源",
    "name_en": "IP Kin-yuen",
    "title": "葉建源, IP Kin-yuen",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.574994206,
    "coord2D": 0.205030918
  },
  {
    "index": 36,
    "name_ch": "葛珮帆",
    "name_en": "Elizabeth QUAT",
    "title": "葛珮帆, Elizabeth QUAT",
    "summary": "Geographical Constituency – New Territories East",
    "image": "https://www.legco.gov.hk/images/mem_1620/qe.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.779592156,
    "coord2D": -0.212365523
  },
  {
    "index": 37,
    "name_ch": "廖長江",
    "name_en": "Martin LIAO",
    "title": "廖長江, Martin LIAO",
    "summary": "Functional Constituency - Commercial (Second)",
    "image": "https://www.legco.gov.hk/images/mem_1620/lck.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.940702379,
    "coord2D": 0.161776438
  },
  {
    "index": 38,
    "name_ch": "潘兆平",
    "name_en": "POON Siu-ping",
    "title": "潘兆平, POON Siu-ping",
    "summary": "Functional Constituency - Labour",
    "image": "https://www.legco.gov.hk/images/mem_1620/psp.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.710337818,
    "coord2D": -0.287058979
  },
  {
    "index": 39,
    "name_ch": "蔣麗芸",
    "name_en": "Dr CHIANG Lai-wan",
    "title": "蔣麗芸, Dr CHIANG Lai-wan",
    "summary": "Geographical Constituency – Kowloon West",
    "image": "https://www.legco.gov.hk/images/mem_small_1620/clw.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.806685805,
    "coord2D": -0.219618797
  },
  {
    "index": 40,
    "name_ch": "盧偉國",
    "name_en": "Ir Dr LO Wai-kwok",
    "title": "盧偉國, Ir Dr LO Wai-kwok",
    "summary": "Functional Constituency - Engineering",
    "image": "https://www.legco.gov.hk/images/mem_1620/lwk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.926315367,
    "coord2D": 0.101309143
  },
  {
    "index": 41,
    "name_ch": "鍾國斌",
    "name_en": "CHUNG Kwok-pan",
    "title": "鍾國斌, CHUNG Kwok-pan",
    "summary": "Functional Constituency - Textiles and Garment",
    "image": "https://www.legco.gov.hk/images/mem_1620/ckpf.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.921232283,
    "coord2D": 0.389013141
  },
  {
    "index": 42,
    "name_ch": "楊岳橋",
    "name_en": "Alvin YEUNG",
    "title": "楊岳橋, Alvin YEUNG",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.73733592,
    "coord2D": -0.05431401
  },
  {
    "index": 43,
    "name_ch": "尹兆堅",
    "name_en": "Andrew WAN",
    "title": "尹兆堅, Andrew WAN",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.650637269,
    "coord2D": -0.141188636
  },
  {
    "index": 44,
    "name_ch": "朱凱廸",
    "name_en": "CHU Hoi-dick",
    "title": "朱凱廸, CHU Hoi-dick",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.931699157,
    "coord2D": -0.070847802
  },
  {
    "index": 45,
    "name_ch": "吳永嘉",
    "name_en": "Jimmy NG",
    "title": "吳永嘉, Jimmy NG",
    "summary": "Functional Constituency - Industrial (Second)",
    "image": "https://www.legco.gov.hk/images/mem_1620/nwk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.94027853,
    "coord2D": 0.115410961
  },
  {
    "index": 46,
    "name_ch": "何君堯",
    "name_en": "Dr Junius HO",
    "title": "何君堯, Dr Junius HO",
    "summary": "Geographical Constituency - New Territories West",
    "image": "https://www.legco.gov.hk/images/mem_1620/hky.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.830408633,
    "coord2D": 0.114286095
  },
  {
    "index": 47,
    "name_ch": "何啟明",
    "name_en": "HO Kai-ming",
    "title": "何啟明, HO Kai-ming",
    "summary": "",
    "image": "",
    "camp": "pro-establishment",
    "coord1D": -0.719986081,
    "coord2D": -0.330816299
  },
  {
    "index": 48,
    "name_ch": "林卓廷",
    "name_en": "LAM Cheuk-ting",
    "title": "林卓廷, LAM Cheuk-ting",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.647348046,
    "coord2D": -0.150390103
  },
  {
    "index": 49,
    "name_ch": "周浩鼎",
    "name_en": "Holden CHOW",
    "title": "周浩鼎, Holden CHOW",
    "summary": "Functional Constituency - District Council (Second)",
    "image": "https://www.legco.gov.hk/images/mem_1620/chdh.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.780506313,
    "coord2D": -0.211527526
  },
  {
    "index": 50,
    "name_ch": "邵家輝",
    "name_en": "SHIU Ka-fai",
    "title": "邵家輝, SHIU Ka-fai",
    "summary": "Functional Constituency - Wholesale & Retail",
    "image": "https://www.legco.gov.hk/images/mem_small_1620/skf.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.950804055,
    "coord2D": 0.309792548
  },
  {
    "index": 51,
    "name_ch": "邵家臻",
    "name_en": "SHIU Ka-chun",
    "title": "邵家臻, SHIU Ka-chun",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.76335144,
    "coord2D": 0.235892102
  },
  {
    "index": 52,
    "name_ch": "柯創盛",
    "name_en": "Wilson OR",
    "title": "柯創盛, Wilson OR",
    "summary": "Geographical Constituency - Kowloon East",
    "image": "https://www.legco.gov.hk/images/mem_1620/ocs.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.783479989,
    "coord2D": -0.201517835
  },
  {
    "index": 53,
    "name_ch": "容海恩",
    "name_en": "YUNG Hoi-yan",
    "title": "容海恩, YUNG Hoi-yan",
    "summary": "Geographical Constituency - New Territories East",
    "image": "https://www.legco.gov.hk/images/mem_small_1620/yhy.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.803949594,
    "coord2D": 0.2463976
  },
  {
    "index": 54,
    "name_ch": "陳沛然",
    "name_en": "Dr Pierre CHAN",
    "title": "陳沛然, Dr Pierre CHAN",
    "summary": "Functional Constituency - Medical",
    "image": "https://www.legco.gov.hk/images/mem_1620/cp.jpg",
    "camp": "non pro-establishment",
    "coord1D": 0.003774776,
    "coord2D": -0.29529652
  },
  {
    "index": 55,
    "name_ch": "陳振英",
    "name_en": "CHAN Chun-ying",
    "title": "陳振英, CHAN Chun-ying",
    "summary": "Functional Constituency - Finance",
    "image": "https://www.legco.gov.hk/images/mem_1620/ccy.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.908577442,
    "coord2D": 0.0396173
  },
  {
    "index": 56,
    "name_ch": "陳淑莊",
    "name_en": "Tanya CHAN",
    "title": "陳淑莊, Tanya CHAN",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.738220334,
    "coord2D": -0.104312718
  },
  {
    "index": 57,
    "name_ch": "張國鈞",
    "name_en": "CHEUNG Kwok-kwan",
    "title": "張國鈞, CHEUNG Kwok-kwan",
    "summary": "Geographical Constituency - Hong Kong Island",
    "image": "https://www.legco.gov.hk/images/mem_1620/ckk.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.790188491,
    "coord2D": -0.227701336
  },
  {
    "index": 58,
    "name_ch": "許智峯",
    "name_en": "HUI Chi-fung",
    "title": "許智峯, HUI Chi-fung",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.650086582,
    "coord2D": -0.121493243
  },
  {
    "index": 59,
    "name_ch": "陸頌雄",
    "name_en": "LUK Chung-hung",
    "title": "陸頌雄, LUK Chung-hung",
    "summary": "Functional Constituency - Labour",
    "image": "https://www.legco.gov.hk/images/mem_1620/lch.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.706403971,
    "coord2D": -0.348975837
  },
  {
    "index": 60,
    "name_ch": "劉國勳",
    "name_en": "LAU Kwok-fan",
    "title": "劉國勳, LAU Kwok-fan",
    "summary": "Functional Constituency - District Council (First)",
    "image": "https://www.legco.gov.hk/images/mem_1620/lkfe.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.786514997,
    "coord2D": -0.226673841
  },
  {
    "index": 61,
    "name_ch": "劉業強",
    "name_en": "Kenneth LAU",
    "title": "劉業強, Kenneth LAU",
    "summary": "Functional Constituency - Heung Yee Kuk",
    "image": "https://www.legco.gov.hk/images/mem_1620/lik.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.889606774,
    "coord2D": 0.117137417
  },
  {
    "index": 62,
    "name_ch": "鄭松泰",
    "name_en": "Dr CHENG Chung-tai",
    "title": "鄭松泰, Dr CHENG Chung-tai",
    "summary": "Geographical Constituency - New Territories West",
    "image": "https://www.legco.gov.hk/images/mem_1620/cct.jpg",
    "camp": "non pro-establishment",
    "coord1D": 0.96636039,
    "coord2D": -0.257191867
  },
  {
    "index": 63,
    "name_ch": "鄺俊宇",
    "name_en": "KWONG Chun-yu",
    "title": "鄺俊宇, KWONG Chun-yu",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.658360004,
    "coord2D": -0.147517934
  },
  {
    "index": 64,
    "name_ch": "譚文豪",
    "name_en": "Jeremy TAM",
    "title": "譚文豪, Jeremy TAM",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.743509233,
    "coord2D": -0.094179675
  },
  {
    "index": 65,
    "name_ch": "范國威",
    "name_en": "Gary FAN",
    "title": "范國威, Gary FAN",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.81317693,
    "coord2D": -0.277488947
  },
  {
    "index": 66,
    "name_ch": "區諾軒",
    "name_en": "AU Nok-hin",
    "title": "區諾軒, AU Nok-hin",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.881794572,
    "coord2D": -0.092123628
  },
  {
    "index": 67,
    "name_ch": "鄭泳舜",
    "name_en": "Vincent CHENG",
    "title": "鄭泳舜, Vincent CHENG",
    "summary": "Geographical Constituency - Kowloon West",
    "image": "https://www.legco.gov.hk/images/mem_1620/cws.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.768149257,
    "coord2D": -0.182480514
  },
  {
    "index": 68,
    "name_ch": "謝偉銓",
    "name_en": "Tony TSE",
    "title": "謝偉銓, Tony TSE",
    "summary": "Functional Constituency - Architectural, Surveying, Planning and Landscape",
    "image": "https://www.legco.gov.hk/images/mem_1620/twct.jpg",
    "camp": "pro-establishment",
    "coord1D": -0.923680246,
    "coord2D": 0.383164227
  },
  {
    "index": 69,
    "name_ch": "陳凱欣",
    "name_en": "CHAN Hoi-yan",
    "title": "陳凱欣, CHAN Hoi-yan",
    "summary": "",
    "image": "",
    "camp": "pro-establishment",
    "coord1D": -0.760940671,
    "coord2D": -0.169076011
  },
  {
    "index": 70,
    "name_ch": "梁國雄",
    "name_en": "LEUNG Kwok-hung",
    "title": "梁國雄, LEUNG Kwok-hung",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.959982097,
    "coord2D": 0.280061692
  },
  {
    "index": 71,
    "name_ch": "羅冠聰",
    "name_en": "Nathan LAW",
    "title": "羅冠聰, Nathan LAW",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.971392393,
    "coord2D": 0.08527451
  },
  {
    "index": 72,
    "name_ch": "姚松炎",
    "name_en": "Dr YIU Chung-yim",
    "title": "姚松炎, Dr YIU Chung-yim",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.84795481,
    "coord2D": 0.474762499
  },
  {
    "index": 73,
    "name_ch": "劉小麗",
    "name_en": "Dr LAU Siu-lai",
    "title": "劉小麗, Dr LAU Siu-lai",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": 0.842897117,
    "coord2D": 0.094275661
  },
  {
    "index": 74,
    "name_ch": "梁頌恆",
    "name_en": "Sixtus LEUNG",
    "title": "梁頌恆, Sixtus LEUNG",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": "",
    "coord2D": ""
  },
  {
    "index": 75,
    "name_ch": "游蕙禎",
    "name_en": "YAU Wai-ching",
    "title": "游蕙禎, YAU Wai-ching",
    "summary": "",
    "image": "",
    "camp": "non pro-establishment",
    "coord1D": "",
    "coord2D": ""
  }
];

export default memberData
